//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car_rental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class rent
    {
        public int rent_id { get; set; }
        public int admin_id { get; set; }
        public int car_id { get; set; }
        public int client_id { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> rent_date { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual car car { get; set; }
        public virtual client client { get; set; }
    }
}
